### PR TITLE
docs: Update README

### LINKED ISSUE #6: docs: Update the documentation
This is a tracking issue for updating the documentation of Polygon's UI.

### PR DESCRIPTION
**Pull request by ejcheng**
This is very much a work-in-progress, but here is some documentation that I was able to write. We can refine this much more later.

Closes #6.

### CODE REVIEW

**Comment by ejcheng** [comment]
Also, there are many other services that can be used to host sites, in addition to Vercel. How would we handle those?

**Comment by mikayelgr** [comment]
Hey, thanks for the PR! I think Netlify also supports one-click hosting solutions, very similar to the one that Vercel has. Netlify x Vercel should be enough I think.

**Comment by ejcheng** [comment]
> Hey, thanks for the PR! I think Netlify also supports one-click hosting solutions, very similar to the one that Vercel has. Netlify x Vercel should be enough I think.

Done!

Also, while a README may be sufficient for now, I think in the future we would need to host a markdown documentation site at docs.polygon.am.

**Comment by mikayelgr** [comment]
Thanks for adding them and creating a base for the README, I will make some changes too, and yes, the idea regarding docs.polygon.am, seems doable.

**Comment by mikayelgr** [comment]
I have found a very nice solution for documenting this: https://github.com/retypeapp/retype

This could also be used for documenting everything else related to Polygon.

**Comment by ejcheng** [comment]
> I have found a very nice solution for documenting this: [retypeapp/retype](https://github.com/retypeapp/retype)
> 
> This could also be used for documenting everything else related to Polygon.

This would work very well! Just to give you a heads up, I'm about to enter exam season, so I might not be able to devote as much time to Polygon as I would like for the next month or two. I can try to get a working retype website prototype with custom configured stuff up in the next week or so.

**Comment by mikayelgr** [comment]
> > I have found a very nice solution for documenting this: [retypeapp/retype](https://github.com/retypeapp/retype)
> 
> > 
> 
> > This could also be used for documenting everything else related to Polygon.
> 
> 
> 
> This would work very well! Just to give you a heads up, I'm about to enter exam season, so I might not be able to devote as much time to Polygon as I would like for the next month or two. I can try to get a working retype website prototype with custom configured stuff up in the next week or so.

Got it, no worries. Thanks for the heads up and good luck on your exams!

**Comment by ejcheng** [comment]
> > > I have found a very nice solution for documenting this: [retypeapp/retype](https://github.com/retypeapp/retype)
> > 
> > 
> > > 
> > 
> > 
> > > This could also be used for documenting everything else related to Polygon.
> > 
> > 
> > This would work very well! Just to give you a heads up, I'm about to enter exam season, so I might not be able to devote as much time to Polygon as I would like for the next month or two. I can try to get a working retype website prototype with custom configured stuff up in the next week or so.
> 
> Got it, no worries. Thanks for the heads up and good luck on your exams!

Thank you! :)

**Comment by mikayelgr** [comment]
Should be fine now.

**Comment by michaelgrigoryan25** [comment]
Closes #6

**Pull request merged**
